import React, { useState } from 'react'
import { Link, routes } from '@redwoodjs/router'
import { Metadata } from '@redwoodjs/web'
import Header from 'src/components/Header/Header'
import SupportImage from '../../../public/support.png'
import HeroSection from 'src/components/HeroSection/HeroSection'
import Accordians from 'src/components/Accordians/Accordians'

const SupportPage = () => {
  const [tab, setTab] = useState('tab1')

  const dataTab1 = [
    {
      question: 'What is GST?',
      answer:
        'GST (Goods and Services Tax) is an indirect tax levied on the supply of goods and services in India.',
    },
    {
      question: 'Why is GST charged on adding cash?',
      answer:
        'As per the law implemented on October 1st, 2023, a 28% GST applies to all deposits made by users on online gaming platforms.',
    },
    {
      question:
        'I received cashback equal to the GST amount. Do I need to pay it separately?',
      answer:
        'No. Raay automatically deducts the 28% GST from your deposit and credits the same amount as cashback within the platform. You can use this cashback freely.',
    },
    {
      question: 'How much GST is charged?',
      answer: 'A flat 28% GST is applicable on the deposit amount.',
    },
    {
      question: 'How is the GST calculated?',
      answer:
        "Let's say you deposit ₹100. After a 28% GST deduction of ₹21.88, your account will reflect ₹78.12. However, you'll receive an instant cashback of ₹21.88 usable within the platform.",
    },
    {
      question: 'Who charges the GST?',
      answer:
        'The Indian government imposes a 28% GST on deposits. Raay acts solely as a collection agent, remitting the tax amount to the government.',
    },
  ]

  const dataTab2 = [
    {
      question:
        'How much time will it take for the payment confirmation & can I withdraw money anytime?',
      answer:
        'All the payments get confirmed within 2 to 24 hrs. Also, yes, you can withdraw your winnings at any time. However, keep in mind that you can withdraw winnings up to a maximum of Rs.2000.',
    },
    {
      question: 'Why is my withdrawal getting failed?',
      answer:
        'All the failed payments will instantly get refunded into your probo wallet. Sometimes the withdrawal fails because of internet connection, power failure, too many transactions processed in one go, and such.',
    },
    {
      question: 'I did not get my withdrawal money, what do I do?',
      answer:
        'If the withdrawal is successful, we will share the UTR number generated by our payment gateway. Alternatively, you can check your updated bank statement to date.',
    },
    {
      question:
        'How much time it will take for payment confirmation or refund of failed transactions?',
      answer:
        'All the payments are confirmed within 2 hrs maximum, and all the failed transactions will be credited to the source account within 5 to 7 business days. If not, kindly contact us!',
    },
  ]

  const dataTab3 = [
    {
      question: 'When will the event be settled?',
      answer:
        'All the events are settled within 24 to 48 hrs, from the time of event expiry.',
    },
    {
      question:
        "The Event should have been closed on 'YES', but it got closed on 'No'. Why?",
      answer:
        'Usually, this does not happen. However, if you face this issue, contact us and we will get this checked with the team and will get back to you within 24 hrs.',
    },
    {
      question:
        'I have won the trade but facing problems with the rewards. What to do?',
      answer:
        'If you face this issue, contact us and we will get this checked with the team and will get back to you within 24 hrs.',
    },
    {
      question: 'Why am I not able to exit the trade?',
      answer: 'You can only exit from matched trades before an event expiry.',
    },
  ]

  const dataTab4 = [
    {
      question: 'When will I be required to do KYC?',
      answer:
        'You will be required to do KYC at two levels. First at the minute your lifetime recharge reaches ₹6000 and then at the time of first withdrawal irrespective of the amount.',
    },
    {
      question:
        "How can I delete my KYC?",
      answer:
        'Once KYC is approved it cannot be changed.',
    },
    {
      question:
        'Want to remove the existing PAN card and add another PAN Card?',
      answer:
        "If the user's KYC is not verified, they have the option to change their PAN details directly from the app. To do so, follow these steps: Click on 'Pro Wallet' located in the top right corner, then select 'My Balance' followed by 'Account Verified.' From there, choose the top option 'Re-do KYC' and click on 'Submit.' After the old KYC is removed, you can proceed to add the new PAN details. Keep in mind that re-doing the KYC will incur a charge of Rs 10 from your deposits, so make sure to recharge your account before initiating the process.",
    },
    {
      question: 'Want to add other bank details or change the existing details?',
      answer: 'You can add up to 2 bank details of the same PAN card entered by the user.',
    },
    {
      question: "Can I use someone else's PAN card with my bank details?",
      answer: 'No, you cannot use someone else s PAN Card with your bank details. The PAN and bank details should be of the same person.',
    },
  ]

  return (
    <>
      <Metadata title="Support" description="Support page" />
      <HeroSection
        imgSrc={SupportImage}
        heading="Let us help you"
        paragraph="Have questions about our product or features? We're here to help and answer any questions you might have"
      />
      <div className="divider"></div>
      <div className="grid grid-cols-4 gap-4 my-4 mx-5">
        <div className="col-span-1 flex flex-col space-y-2">
          <h2 className="text-4xl font-bold text-primary mb-2">FAQs</h2>
          <button
            className={`btn btn-ghost justify-start  ${
              tab === 'tab1' ? 'text-secondary' : ''
            }`}
            onClick={() => setTab('tab1')}
          >
            FAQs on GST
          </button>
          <button
            className={`btn btn-ghost justify-start ${
              tab === 'tab2' ? 'text-secondary' : ''
            }`}
            onClick={() => setTab('tab2')}
          >
            FAQs on Payments
          </button>
          <button
            className={`btn btn-ghost justify-start ${
              tab === 'tab3' ? 'text-secondary' : ''
            }`}
            onClick={() => setTab('tab3')}
          >
            FAQs on Trading
          </button>
          <button
            className={`btn btn-ghost justify-start ${
              tab === 'tab4' ? 'text-secondary' : ''
            }`}
            onClick={() => setTab('tab4')}
          >
            FAQs on KYC
          </button>
        </div>
        <div className="col-span-3">
          {tab === 'tab1' &&
            dataTab1.map((faq, faqIndex) => (
              <Accordians
                key={faqIndex}
                heading={faq.question}
                body={faq.answer}
              />
            ))}
          {tab === 'tab2' &&
            dataTab2.map((faq, faqIndex) => (
              <Accordians
                key={faqIndex}
                heading={faq.question}
                body={faq.answer}
              />
            ))}
          {tab === 'tab3' &&
            dataTab3.map((faq, faqIndex) => (
              <Accordians
                key={faqIndex}
                heading={faq.question}
                body={faq.answer}
              />
            ))}
          {tab === 'tab4' &&
            dataTab4.map((faq, faqIndex) => (
              <Accordians
                key={faqIndex}
                heading={faq.question}
                body={faq.answer}
              />
            ))}
        </div>
      </div>
      <div className="divider"></div>
    </>
  )
}

export default SupportPage
